### ISSUE TITLE
Really cool project!

### ISSUE THREAD

**Issue by hoytech** [bertdobbelaere/SorterHunter#1]
FYI, we discuss sorting network stuff in the issue tracker for the perl module Algorithm::Networksort written by @jgamble . @Morwenn pointed us to your work in the following issue:

https://github.com/jgamble/Algorithm-Networksort/issues/23

The module tries to maintain a list of "best" sorting networks too, and would like to incorporate your research.

Cheers!

**Comment by bertdobbelaere** [comment]
Thanks!
