### ISSUE TITLE
New sorting network for 20 inputs with 91 CEs

### ISSUE THREAD

**Issue by Morwenn** [bertdobbelaere/SorterHunter#2]
You might want to complete your README and/or your list of sorting networks with the new result from [*Enhanced Optimization with CompositeObjectives and Novelty Pulsation*][1] by Shahrzad & al. which provides a new network sorting 20 inputs with 91 comparators (I don't know about the number of layers).

The paper claims a new world record for this network but doesn't mention your project, so I doubt that the authors know about it :)

  [1]: https://arxiv.org/pdf/1906.04050.pdf

**Comment by bertdobbelaere** [comment]
Thanks for letting me know. I have notified the authors.
