### ISSUE TITLE
Sorting network for 8 inputs Visual

### ISSUE THREAD

**Issue by Control55** [bertdobbelaere/SorterHunter#3]
Update the visual of the 8 input Sorting network, to match the description: 

![8-input Sorting network](https://user-images.githubusercontent.com/68385620/111835903-dcefcc00-88f5-11eb-9e53-a06fe05ec4be.png)

This would also be more consistent with greater sorting networks, and with bitonic-type Sorting networks.

(and please check your mail, I've sent you something)

**Comment by bertdobbelaere** [comment]
Updated image generation algorithm. 2nd layer looks better now. Thanks for the suggestion.
