### ISSUE TITLE
Depth Optimality Proof for n=9 and n=10

### ISSUE THREAD

**Issue by Topsii** [bertdobbelaere/SorterHunter#4]
The optimal depth for n=9 and n=10 was proven by Ian Parberry in [_A Computer Assisted Optimal Depth Lower Bound for
Nine-Input Sorting Networks_](http://ianparberry.com/pubs/9-input.pdf). I think it was first published as [_A computer assisted optimal depth lower bound for sorting networks with nine inputs_](https://dl.acm.org/doi/10.1145/76263.76280) in Supercomputing '89: Proceedings of the 1989 ACM/IEEE conference on Supercomputing.

**Comment by bertdobbelaere** [comment]
Update the table, thanks for the suggestion.
